### ISSUE TITLE
AERPAW Portal Data Migration - v1 to v2

### ISSUE THREAD

**Issue by mjstealey** [AERPAW-Platform-Control/aerpaw-portal#33]
# AERPAW Data Migration for v1 to v2

## Task list

Migration script preserved in the `v1-to-v2-migration` directory

- [x] extract v1 portal data as JSON dump files
  - accounts.json
  - experiments.json
  - profiles.json
  - projects.json
  - reservations.json
  - resources.json
  - user_groups.json
  - usercomms.json
- [x] develop v1-to-v2 migration mapping as python script
  - `migrate-v1-to-v2.py`
- [x] export v2 compliant data objects based on v1 import files - save as JSON fixture files
  - credentials.json
  - experiments.json
  - operations.json
  - profiles.json
  - projects.json
  - resources.json
  - users.json

## Reference information

Django database tables for v2 that would potentially be populated by migration from v1 

### Database tables

```
                             List of relations
 Schema |                     Name                      | Type  |  Owner
--------+-----------------------------------------------+-------+----------
 public | auth_group                                    | table | postgres
 public | auth_group_permissions                        | table | postgres
 public | auth_permission                               | table | postgres
 public | credentials_publiccredentials                 | table | postgres
 public | django_admin_log                              | table | postgres
 public | django_content_type                           | table | postgres
 public | django_migrations                             | table | postgres
 public | django_session                                | table | postgres
 public | experiment_files_experimentfile               | table | postgres
 public | experiments_aerpawexperiment                  | table | postgres
 public | experiments_aerpawexperiment_experiment_files | table | postgres
 public | experiments_aerpawexperiment_resources        | table | postgres
 public | experiments_canonicalexperimentresource       | table | postgres
 public | experiments_experimentsession                 | table | postgres
 public | experiments_userexperiment                    | table | postgres
 public | operations_canonicalnumber                    | table | postgres
 public | profiles_aerpawuserprofile                    | table | postgres
 public | projects_aerpawproject                        | table | postgres
 public | projects_userproject                          | table | postgres
 public | resources_aerpawresource                      | table | postgres
 public | user_messages_aerpawusermessage               | table | postgres
 public | user_messages_aerpawusermessage_received_by   | table | postgres
 public | user_requests_aerpawuserrequest               | table | postgres
 public | user_requests_aerpawuserrequest_received_by   | table | postgres
 public | users_aerpawuser                              | table | postgres
 public | users_aerpawuser_groups                       | table | postgres
 public | users_aerpawuser_user_permissions             | table | postgres
```

### Migration

Migration to be framed in terms of v2 portal app data as they get populated from v1 app data
  
v2 apps

- `credentials`
- `experiment_files`
- `experiments`
- `operations`
- `profiles`
- `projects`
- `resources`
- `user_messages`
- `user_requests`
- `users`

v1 apps

- `accounts`
- `projects`
- `experiments`
- `reservations`
- `resources`
- `profiles`
- `cicd`
- `user_groups`
- `usercomms`

## Roles - part of v2 standard deployment (`auth.group` table)

File `aerpaw_roles.json` resides in the [/portal/apps/users/fixtures]() directory

```json
[
  {
    "model": "auth.group",
    "pk": 1,
    "fields": {
      "name": "experimenter",
      "permissions": []
    }
  },
  {
    "model": "auth.group",
    "pk": 2,
    "fields": {
      "name": "pi",
      "permissions": []
    }
  },
  {
    "model": "auth.group",
    "pk": 3,
    "fields": {
      "name": "operator",
      "permissions": []
    }
  },
  {
    "model": "auth.group",
    "pk": 4,
    "fields": {
      "name": "site_admin",
      "permissions": []
    }
  }
]
```

## v2 app `credentials`

Example fixture entry

```json
{
  "model": "credentials.publiccredentials",
  "pk": 1,
  "fields": {
    "created": "2022-08-11T13:19:03.437Z",
    "modified": "2022-08-11T19:24:49.469Z",
    "created_by": "stealey@unc.edu",
    "modified_by": "stealey@unc.edu",
    "expiry_date": "2022-08-11T19:24:49.469Z",
    "is_deleted": true,
    "name": "stealey demo key",
    "owner": 1,
    "public_credential": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQ...vnkeWKcBsP1f6BCymVCZ9gBoJDBYwry9",
    "uuid": "d641cef8-bd70-443e-9345-ee8c5d6d32d2"
  }
},
```

## v2 app `experiment_files`

Example fixture entry

```json
{
  "model": "experiment_files.experimentfile",
  "pk": 61,
  "fields": {
    "created": "2022-10-03T23:01:46.536Z",
    "modified": "2022-10-03T23:01:46.624Z",
    "created_by": "snagara9@ncsu.edu",
    "modified_by": "snagara9@ncsu.edu",
    "is_active": true,
    "is_deleted": false,
    "file_location": "/home/aerpawops/experiments/1a03cba3-1fbc-4a9d-84c2-bc9af3e30659/aerpaw-XM-X0004-common.ovpn",
    "file_name": "aerpaw-XM-X0004-common.ovpn",
    "file_type": "ovpn",
    "file_notes": null,
    "uuid": "fc7c888f-cfd8-481e-b6f1-7e415530993a"
  }
},
```

## v2 app `experiments`

Example fixture entry

```json
{
  "model": "experiments.aerpawexperiment",
  "pk": 4,
  "fields": {
    "created": "2022-08-22T17:14:52.864Z",
    "modified": "2022-11-07T04:27:43.208Z",
    "created_by": "snagara9@ncsu.edu",
    "modified_by": "snagara9@ncsu.edu",
    "canonical_number": 4,
    "description": "Test Exp 4",
    "experiment_creator": 7,
    "experiment_flags": "000",
    "experiment_state": "saved",
    "is_canonical": true,
    "is_deleted": false,
    "is_emulation_required": true,
    "is_retired": false,
    "name": "Exp_4",
    "project": 4,
    "resources_locked": true,
    "uuid": "1a03cba3-1fbc-4a9d-84c2-bc9af3e30659",
    "experiment_files": [
      60,
      61
    ],
    "resources": [
      4,
      1
    ]
  }
},
{
  "model": "experiments.userexperiment",
  "pk": 6,
  "fields": {
    "experiment": 4,
    "granted_by": 7,
    "granted_date": "2022-08-22T17:14:52.867Z",
    "user": 7
  }
},
{
  "model": "experiments.experimentsession",
  "pk": 9,
  "fields": {
    "created": "2022-09-28T14:14:16.061Z",
    "modified": "2022-09-28T16:47:35.665Z",
    "created_by": "snagara9@ncsu.edu",
    "modified_by": "snagara9@ncsu.edu",
    "ended_by": 7,
    "end_date_time": "2022-09-28T16:47:35.665Z",
    "experiment": 4,
    "is_active": false,
    "session_type": "development",
    "started_by": 7,
    "start_date_time": "2022-09-28T16:45:23.814Z",
    "uuid": "c1e9c9be-2e65-4a34-b2e1-d11f77513282"
  }
},
{
  "model": "experiments.canonicalexperimentresource",
  "pk": 8,
  "fields": {
    "created": "2022-08-23T18:11:20.961Z",
    "modified": "2022-10-17T17:22:36.271Z",
    "experiment": 4,
    "experiment_node_number": 2,
    "node_display_name": "UAV",
    "node_type": "aprn",
    "node_uhd": "1.3.3",
    "node_vehicle": "vehicle_none",
    "resource": 4,
    "uuid": ""
  }
},
```

## v2 app `operations`

Example fixture entry

```json
{
  "model": "operations.canonicalnumber",
  "pk": 1,
  "fields": {
    "created": "2022-08-05T20:23:41.768Z",
    "modified": "2022-08-05T20:23:41.768Z",
    "canonical_number": 1,
    "is_deleted": false,
    "is_retired": false
  }
},
```

## v2 app `profiles`

Example fixture entry

```json
{
  "model": "profiles.aerpawuserprofile",
  "pk": 1,
  "fields": {
    "created": "2022-07-14T14:29:24.423Z",
    "modified": "2022-12-01T01:24:14.764Z",
    "created_by": "stealey@unc.edu",
    "modified_by": "stealey@unc.edu",
    "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...0RF92qNWmRIVQW_76Pr2BkkkJHmQ6m9rS6agyCntiZc",
    "employer": "RENCI - UNC Chapel Hill",
    "position": "Distributed Systems Software Engineer",
    "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...8YQl5YJxE6w4TBWFgdZZskzGZfYhhl2nrzW-0uRoRz0",
    "research_field": null,
    "uuid": "1047126b-9301-440f-b8e3-9978c15206c4"
  }
},
```

## v2 app `projects`

Example fixture entry

```json
{
  "model": "projects.aerpawproject",
  "pk": 4,
  "fields": {
    "created": "2022-08-22T17:09:49.683Z",
    "modified": "2022-08-22T17:09:49.683Z",
    "created_by": "snagara9@ncsu.edu",
    "modified_by": "snagara9@ncsu.edu",
    "description": "Sudhanva dummy project",
    "is_deleted": false,
    "is_public": false,
    "name": "snagara9_test_project",
    "project_creator": 7,
    "uuid": "b93a3936-afb1-4411-af20-60771fafb3e1"
  }
},
{
  "model": "projects.userproject",
  "pk": 10,
  "fields": {
    "granted_by": 7,
    "granted_date": "2022-08-22T17:09:49.686Z",
    "project": 4,
    "project_role": "project_owner",
    "user": 7
  }
},
```

## v2 app `resources`

Example fixture entry

```json
{
  "model": "resources.aerpawresource",
  "pk": 1,
  "fields": {
    "created": "2022-07-20T20:06:22.244Z",
    "modified": "2022-10-26T23:39:25.844Z",
    "created_by": "stealey@unc.edu",
    "modified_by": "snagara9@ncsu.edu",
    "description": "Centennial Campus Node 1",
    "hostname": "aerpaw18",
    "ip_address": "152.14.188.101",
    "is_active": true,
    "is_deleted": false,
    "location": "Centennial Campus",
    "name": "CC1",
    "ops_notes": "",
    "resource_class": "allow_canonical",
    "resource_mode": "testbed",
    "resource_type": "AFRN",
    "uuid": "151e8890-0b71-4520-b8da-afc2a2ea3133"
  }
},
```

## v2 app `user_messages`

Example fixture entry

```json
{
  "model": "user_messages.aerpawusermessage",
  "pk": 1,
  "fields": {
    "created": "2022-11-01T19:57:55.569Z",
    "modified": "2022-11-01T19:57:55.580Z",
    "created_by": "mjstealey@gmail.com",
    "modified_by": "mjstealey@gmail.com",
    "is_deleted": false,
    "is_read": false,
    "message_body": "\nrequest_type: role\n\nrequested_by: mj stealey\n\nrequest_note: [pi] - role request\nrequested_date: 11/01/2022, 15:57:55\n\nreceived_by: ['Magreth Mushi', 'Michael J. Stealey', 'Sonali Chaudhari', 'Sudhanva Nagaragadde', 'Yufeng Xin']\n\ncompleted_by: -----\nis_approved: -----\nresponse_note: -----\nresponse_date: -----\n",
    "message_owner": 5,
    "message_subject": "REQUEST: [pi] - role request",
    "read_date": null,
    "sent_by": 4,
    "uuid": "d785e420-4207-452d-8bf8-7204b448db3a",
    "received_by": [
      5,
      1,
      2,
      7,
      3
    ]
  }
},
```

## v2 app `user_requests`

Example fixture entry

```json
{
  "model": "user_requests.aerpawuserrequest",
  "pk": 8,
  "fields": {
    "created": "2022-12-08T17:40:23.622Z",
    "modified": "2022-12-08T19:44:58.305Z",
    "created_by": "mjstealey@gmail.com",
    "modified_by": "mjmushi@ncsu.edu",
    "completed_by": 5,
    "completed_date": "2022-12-08T19:44:58.305Z",
    "is_approved": true,
    "request_note": "[pi] - role request",
    "request_type": "role",
    "request_type_id": 4,
    "requested_by": 4,
    "response_date": "2022-12-08T19:44:58.305Z",
    "response_note": "Great. I can see the information is pulled under the request note column.",
    "uuid": "faef4700-7c47-415d-9e78-ea888aaf563a",
    "received_by": [
      5,
      1,
      2,
      7,
      3
    ]
  }
}
```

## v2 app `users`

Example fixture entry

```json
{
  "model": "users.aerpawuser",
  "pk": 1,
  "fields": {
    "password": "",
    "last_login": "2022-12-12T20:03:22.882Z",
    "is_superuser": true,
    "username": "stealey@unc.edu",
    "first_name": "Michael",
    "last_name": "Stealey",
    "email": "stealey@unc.edu",
    "is_staff": true,
    "is_active": true,
    "date_joined": "2022-07-14T14:29:24Z",
    "created": "2022-07-14T14:29:24.421Z",
    "modified": "2022-12-12T20:03:22.873Z",
    "created_by": "stealey@unc.edu",
    "modified_by": "stealey@unc.edu",
    "display_name": "Michael J. Stealey",
    "openid_sub": "http://cilogon.org/serverA/users/242181",
    "profile": 1,
    "uuid": "5376cc65-9d98-4f98-b192-210973f753e2",
    "groups": [
      1,
      2,
      3,
      4
    ],
    "user_permissions": []
  }
},
```

**Comment by mjstealey** [comment]
completed and deployed
