### ISSUE TITLE
v1.0.0 - version 1.0.0 - updates from beta tests

### ISSUE THREAD

**Issue by mjstealey** [AERPAW-Platform-Control/aerpaw-portal#43]
Aggregate of bugs/issues found during beta testing 

- [x] DEBUG: enable when debug is true OR user is site_admin (ref: #36)
- [x] UI: suppress `Operators > Experiment Sessions` for now - add as new work item (ref: #35)  
- [x] API: only allow users with `experimenter` role to be added to projects (ref: #37)
- [x] UI/API: new users need to login in twice - once to create account - second to access account (ref: #38)
- [x] UI: Google form link must be clicked prior to allowing user to creating experiment (ref: #40)
- [x] UI: Submit to testbed should only be allowed after a successful Development session (ref: #41)
- [x] API: email generation - refer to ticket #28 (ref: #42)

**Comment by mjstealey** [comment]
merged, tagged and deployed to NCSU
